dist: trusty
sudo: required
services:
  - docker
language: go
go:
- 1.16
env:
  - GO111MODULE=on

script:
- make test
- make vet

branches:
  only:
  - main
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
